// Scores cross-checked against Biopython 1.88 PairwiseAligner (independent implementation).
// Fixture generated by a script with random sequences; see tests/fixtures/biopython-pairwise.json.
import { describe, expect, it } from 'vitest';
import cases from './fixtures/biopython-pairwise.json';
import { alignPair, type AlignMode } from '../src/core/pairwise';
import { dnaScoring, pairScore, proteinScoring } from '../src/core/matrices';

interface Case { kind: 'dna' | 'protein'; mode: AlignMode; a: string; b: string; go: number; ge: number; score: number }

/** Re-score a gapped alignment independently of the DP. */
function rescore(a: string, b: string, kind: string, mode: AlignMode, go: number, ge: number): number {
  const sc = kind === 'dna' ? dnaScoring('NUC.4.4') : proteinScoring('BLOSUM62');
  let s = 0;
  const L = a.length;
  const firstA = a.search(/[^-]/), lastA = L - 1 - [...a].reverse().join('').search(/[^-]/);
  const firstB = b.search(/[^-]/), lastB = L - 1 - [...b].reverse().join('').search(/[^-]/);
  let prev = '';
  for (let i = 0; i < L; i++) {
    if (a[i] !== '-' && b[i] !== '-') { s += pairScore(sc, a[i], b[i]); prev = ''; continue; }
    const gapIn = a[i] === '-' ? 'A' : 'B';
    const terminal = gapIn === 'A' ? i < firstA || i > lastA : i < firstB || i > lastB;
    const free = (mode === 'semiglobal' && terminal) || (mode === 'fit' && gapIn === 'B' && terminal);
    if (!free) s -= prev === gapIn ? ge : go;
    prev = gapIn;
  }
  return s;
}

describe('cross-check vs Biopython PairwiseAligner', () => {
  for (const [k, c] of (cases as Case[]).entries()) {
    it(`#${k} ${c.kind} ${c.mode} (${c.a.length}×${c.b.length}, gap ${c.go}/${c.ge})`, () => {
      const scoring = c.kind === 'dna' ? dnaScoring('NUC.4.4') : proteinScoring('BLOSUM62');
      const r = alignPair(c.a, c.b, { scoring, gapOpen: c.go, gapExtend: c.ge, mode: c.mode });
      expect(r.score).toBeCloseTo(c.score, 6);
      expect(r.a.length).toBe(r.b.length);
      if (c.mode !== 'local') {
        expect(r.a.replace(/-/g, '')).toBe(c.a);
        expect(r.b.replace(/-/g, '')).toBe(c.b);
        // the traceback must actually achieve the reported score
        expect(rescore(r.a, r.b, c.kind, c.mode, c.go, c.ge)).toBeCloseTo(c.score, 6);
      } else {
        expect(c.a.slice(r.aStart)).toContain(r.a.replace(/-/g, ''));
        expect(rescore(r.a, r.b, c.kind, 'global', c.go, c.ge)).toBeCloseTo(c.score, 6);
      }
    });
  }
});
